# config.py
# This file is auto-generated by a notebook. DO NOT EDIT MANUALLY.

# --- File path configuration ---
DATE_STR = '2025-06-13'
DOWNLOAD_DIR = 'C:\\Users\\ping\\Downloads'
DEST_DIR = 'c:\\Users\\ping\\Files_win10\\python\\py311\\stocks\\data'

# --- Analysis Parameters ---
ANNUAL_RISK_FREE_RATE = 0.04
TRADING_DAYS_YEAR = 252
