# config.py
# This file is auto-generated by py0. DO NOT EDIT MANUALLY.

from pathlib import Path

# --- File path configuration ---
DATE_STR = '2025-12-29'
DOWNLOAD_DIR = Path('C:/Users/ping/Downloads')
DEST_DIR = Path('c:/Users/ping/Files_win10/python/py311/stocks/data')

# --- Analysis Parameters ---
ANNUAL_RISK_FREE_RATE = 0.04
TRADING_DAYS_PER_YEAR = 252
DAILY_RISK_FREE_RATE = 0.00015873015873015873
